spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/formation
    username: formation
    password: formation
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

